<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

namespace GPBMetadata;

class Order
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af1020a0b6f726465722e70726f746f1204676f6d652284010a0c4f7264" .
            "657252657175657374120c0a0475756964180120012809120b0a036f6964" .
            "180220012809120e0a0673796d626f6c180320012809122a0a0b7472616e" .
            "73616374696f6e18042001280e32152e676f6d652e5472616e7361637469" .
            "6f6e54797065120d0a057072696365180520012801120e0a06766f6c756d" .
            "65180620012801222e0a0d4f72646572526573706f6e7365120c0a04636f" .
            "6465180120012805120f0a076d6573736167651802200128092a240a0f54" .
            "72616e73616374696f6e5479706512070a03425559100012080a0453414c" .
            "45100132770a054f7264657212340a07446f4f7264657212122e676f6d65" .
            "2e4f72646572526571756573741a132e676f6d652e4f7264657252657370" .
            "6f6e7365220012380a0b44656c6574654f7264657212122e676f6d652e4f" .
            "72646572526571756573741a132e676f6d652e4f72646572526573706f6e" .
            "73652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

