<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pool.proto

namespace Gome\Pool;

if (false) {
    /**
     * This class is deprecated. Use Gome\Pool\DepthRequest\DepthType instead.
     * @deprecated
     */
    class DepthRequest_DepthType {}
}
class_exists(DepthRequest\DepthType::class);
@trigger_error('Gome\Pool\DepthRequest_DepthType is deprecated and will be removed in the next major release. Use Gome\Pool\DepthRequest\DepthType instead', E_USER_DEPRECATED);

