<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pool.proto

namespace Gome\Pool;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gome.pool.Depth</code>
 */
class Depth extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double p = 1;</code>
     */
    protected $p = 0.0;
    /**
     * Generated from protobuf field <code>double v = 2;</code>
     */
    protected $v = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $p
     *     @type float $v
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pool::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double p = 1;</code>
     * @return float
     */
    public function getP()
    {
        return $this->p;
    }

    /**
     * Generated from protobuf field <code>double p = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setP($var)
    {
        GPBUtil::checkDouble($var);
        $this->p = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double v = 2;</code>
     * @return float
     */
    public function getV()
    {
        return $this->v;
    }

    /**
     * Generated from protobuf field <code>double v = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setV($var)
    {
        GPBUtil::checkDouble($var);
        $this->v = $var;

        return $this;
    }

}

