<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pool.proto

namespace Gome\Pool;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gome.pool.DepthRequest</code>
 */
class DepthRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 偏移量
     *
     * Generated from protobuf field <code>int64 offset = 1;</code>
     */
    protected $offset = 0;
    /**
     * 查询条数
     *
     * Generated from protobuf field <code>int64 count = 2;</code>
     */
    protected $count = 0;
    /**
     * 交易对
     *
     * Generated from protobuf field <code>string symbol = 3;</code>
     */
    protected $symbol = '';
    /**
     * 交易方向
     *
     * Generated from protobuf field <code>.gome.pool.DepthRequest.DepthType transaction = 4;</code>
     */
    protected $transaction = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $offset
     *           偏移量
     *     @type int|string $count
     *           查询条数
     *     @type string $symbol
     *           交易对
     *     @type int $transaction
     *           交易方向
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pool::initOnce();
        parent::__construct($data);
    }

    /**
     * 偏移量
     *
     * Generated from protobuf field <code>int64 offset = 1;</code>
     * @return int|string
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * 偏移量
     *
     * Generated from protobuf field <code>int64 offset = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt64($var);
        $this->offset = $var;

        return $this;
    }

    /**
     * 查询条数
     *
     * Generated from protobuf field <code>int64 count = 2;</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * 查询条数
     *
     * Generated from protobuf field <code>int64 count = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->count = $var;

        return $this;
    }

    /**
     * 交易对
     *
     * Generated from protobuf field <code>string symbol = 3;</code>
     * @return string
     */
    public function getSymbol()
    {
        return $this->symbol;
    }

    /**
     * 交易对
     *
     * Generated from protobuf field <code>string symbol = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSymbol($var)
    {
        GPBUtil::checkString($var, True);
        $this->symbol = $var;

        return $this;
    }

    /**
     * 交易方向
     *
     * Generated from protobuf field <code>.gome.pool.DepthRequest.DepthType transaction = 4;</code>
     * @return int
     */
    public function getTransaction()
    {
        return $this->transaction;
    }

    /**
     * 交易方向
     *
     * Generated from protobuf field <code>.gome.pool.DepthRequest.DepthType transaction = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setTransaction($var)
    {
        GPBUtil::checkEnum($var, \Gome\Pool\DepthRequest_DepthType::class);
        $this->transaction = $var;

        return $this;
    }

}

