<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

namespace Gome;

/**
 * Protobuf type <code>gome.TransactionType</code>
 */
class TransactionType
{
    /**
     * Generated from protobuf enum <code>BUY = 0;</code>
     */
    const BUY = 0;
    /**
     * Generated from protobuf enum <code>SALE = 1;</code>
     */
    const SALE = 1;
}

